base/urls.py
from django.urls import URLPattern, path
from . import views


urlpatterns = [
    # homepage
    path('', views.home, name="home"),
    # other pages str=string pk=primaryvaluekey
    # login page
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
    path('volunteer/', views.volunteerPage, name="volunteer"),
    path('about/', views.aboutPage, name="about"),
    path('contact/', views.contactPage, name="contact"),
    path('volunteerform/', views.volunteerFormPage, name='volunteerForm'),
]

yxefoodbank/urls.py
from django import urls
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import Settings, settings
from django.urls import path, include
from account.views import registration_view
from userHist import views
from donation.views import (SuccessView,
                            CancelView, CreateCheckoutSessionView, DonationLandingPageView)
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('', include('store.urls')),
    path('', include('userHist.urls')),
    path('donation/', DonationLandingPageView.as_view(), name="donationpage"),
    path('success/', SuccessView.as_view(), name='success'),
    path('register/', registration_view, name="register"),
    path('create-checkout-session/<pk>/',
         CreateCheckoutSessionView.as_view(), name='create-checkout-session'),
    path('cancel/', CancelView.as_view(), name='cancel'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yxefoodbank/yxefoodbank/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

account/models.py
from re import L
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
# Create your models here.


class MyAccountManager(BaseUserManager):
    def create_user(self, email, username, first_name, last_name, phone, password=None,):
        # in case fields are left empty
        if not email:
            raise ValueError('Users must have an email address')
        if not username:
            raise ValueError('Users must have a username')
        if not first_name:
            raise ValueError('Users must have a first_name')
        if not last_name:
            raise ValueError('Users must have a last_name')
        if not phone:
            raise ValueError('Users must have a phone number')

        # a base for user creations. this is require information to be filled for a regular account
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            first_name=first_name,
            last_name=last_name,
            phone=phone
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    # super user is required to create staff => is_staff
    def create_superuser(self, email, username, password, first_name, last_name, phone):
        user = self.create_user(
            username=username,
            password=password,
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            phone=phone
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


# account creation restrictions and sql fields
class Account(AbstractBaseUser):
    # data fields, some are generated and some are asked user
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    phone = models.CharField(verbose_name="phone", max_length=10, unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)

    USERNAME_FIELD = 'username'
    # can add more required fields here
    REQUIRED_FIELDS = ['email', 'phone', 'first_name', 'last_name']
    # uses account MyAccountManager to go through each option require to create user
    objects = MyAccountManager()

    # Django requirements, account creation doesn't work without these fields as per documentations
    def __str__(self):
        # kind of like a 'to string' method
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

base/models.py
from pydoc import describe
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
# WHERE WE CONFIGURE DATABASE

store/models.py
import re
from django.db import models
from account.models import Account

# Create your models here.


class Customer(models.Model):
    user = models.OneToOneField(
        Account, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    image = models.ImageField(null=True, blank=True)
    description = models.CharField(max_length=200, null=True)
    calories = models.IntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return self.name


class Form(models.Model):
    customer = models.ForeignKey(
        Account, on_delete=models.SET_NULL, blank=True, null=True)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False, null=True, blank=False)
    transaction_id = models.CharField(max_length=200, null=True)
    notes = models.CharField(default="No Comments", max_length=200, null=True)
    fufilled = models.BooleanField(default=False, null=True, blank=False)

    def __str__(self):
        return str(self.id)


class Formitems(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True)
    form = models.ForeignKey(
        Form, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def add(self):
        self.quantity += 1

    def remove(self):
        self.quantity -= 1

base/views.py
from django.shortcuts import redirect, render

from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Using login required all you have to do is write @login_required line before function
# Create your views here. WHERE WE CONFIGURE OUR PAGES


def home(request):
    # can also be done like this return render(request, 'home.html', {'rooms': rooms})
    return render(request, 'base/home.html')


def volunteerPage(request):
    return render(request, 'base/volunteer.html')


def aboutPage(request):
    return render(request, 'base/about.html')


# recently added volunteer form view
def volunteerFormPage(request):
    return render(request, 'base/volunteerform.html')


def contactPage(request):
    return render(request, 'base/contact.html')


def loginPage(request):
    # if a user is logged in, they can't login again
    if request.user.is_authenticated:
        return redirect('/')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, "User doesn't exist or is deleted.")
        user = authenticate(request, username=username, password=password)

        if user != None:
            login(request, user)
            messages_in_django = messages.get_messages(request)
            for message in messages_in_django:
                pass
            return redirect('/')
        else:
            messages.error(request, "Username or Password is invalid.")
    context = {}
    return render(request, 'base/login.html', context)


def logoutUser(request):
    logout(request)
    return redirect('/')

base/templates/base/about.html
{% extends 'main.html' %} {% block content %}
<div class="container is-max-desktop">
  <div class="notification is-secondary">
    <div class="title">About</div>
    <p class="subtitle">
      YXE Food Bank is one of the regional food banks serving Saskatoon. Through YXE Food Bank's
      network of food distribution facilities, we are able to meet our customers' basic nutritional
      needs. More than 100 agencies, such as soup kitchens, homeless shelters, and religious institutions,
      are part of our network. YXE Food Bank strives to uphold the dignity of those we assist while
      also protecting their health by delivering healthy, culturally appropriate food to those in
      need where it is most needed.
      <br><br>
      <a href="{% url 'contact' %}"> If you have some questions, feel free to contact us.</a>
    </p>
  </div>
</div>

{% endblock content %}

base/templates/base/contact.html
{% extends 'main.html' %} {% block content %}
<div class="container is-fluid">
  <section class="section supage ">
    <div class="tile is-parent " style="line-height: 1.3">
      <form class="tile is-child box" method="POST">
        <div class="title">Contact us</div>
     <!-- First Name -->
     <div class="field" style="line-height:2rem;">
      <label class="label">First Name</label>
      <p class="control has-icons-left has-icons-right">
        <input class="input" type="text" placeholder="First Name" autofocus="" name="first_name" maxlength="30"
          required="" id="id_first_name" />
        <span class="icon is-small is-left">
          <i class="fas fa-f"></i>
        </span>
      </p>
    </div>

    <!-- Last Name -->
    <div class="field">
      <label class="label">Last Name</label>
      <p class="control has-icons-left has-icons-right">
        <input class="input" type="text" placeholder="Last Name" name="last_name" maxlength="30" required=""
          id="id_last_name" />
        <span class="icon is-small is-left">
          <i class="fas fa-l"></i>
        </span>
      </p>
    </div>

    <!-- Email -->
    <div class="field">
      <label class="label">Email</label>
      <p class="control has-icons-left has-icons-right">
        <input class="input" type="email" placeholder="Email" name="email" maxlength="60" required="" id="id_email" />
        <span class="icon is-small is-left">
          <i class="fas fa-envelope"></i>
        </span>
      </p>
    </div>

    <!-- Phone Number -->
    <div class="field">
      <label class="label">Phone Number</label>
      <p class="control has-icons-left has-icons-right">
        <input class="input" type="tel" pattern="[0-9]{10}" placeholder="3061234567" name="phone" maxlength="10"
          required="" id="id_phone" />
        <span class="icon is-small is-left">
          <i class="fas fa-phone"></i>
        </span>
      </p>
    </div>

    <!--Question-->
    <div class="field">
      <label class="label">Comments</label>
      <p class="control has-icons-left has-icons-right">
        <textarea class="textarea" placeholder="e.g. Comments"></textarea>
        <span class="icon is-small is-left">
          <i class="fas fa-Q"></i>
      </p>
  </div>

    <!--Donate Button-->
  <div class="field">
      <p class="control">
        <br style="display:block; margin: 5px 0;">
        <button class="button is-primary is-light">Send</button>
      </p>
    </div>
      </form>
  
      <div class="tile is-parent is-5">
        <article class="tile is-child box suloginbox">
          <p id="yui_3_17_2_1_1647900213026_591">
            <div class="title">Main Office</div>
            100 Avenue B East
          <br>
            Saskatoon, SK S7K 2K5
          <br><br>
            Phone: 306-200-0000
         <br>
              <a href="mailto:yxefoodbanksask@gmail.ca" tabindex="0">yxefoodbanksask@gmail.ca</a></p></h3>
         <p></p>
        </article>
      </div>
    </div>
  </section>
</div>

{% endblock content %}

base/templates/base/contactform.html
{% extends 'main.html' %} 
{% block content %}
<div class="container">
  <div class="notification is-primary">
    <div class="title">Contact Us</div>


    <!-- First Name -->
    <div class="field" style="line-height:2rem;">
        <label class="label">First Name</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="text" placeholder="First Name" autofocus="" name="first_name" maxlength="30"
            required="" id="id_first_name" />
          <span class="icon is-small is-left">
            <i class="fas fa-f"></i>
          </span>
        </p>
      </div>
  
      <!-- Last Name -->
      <div class="field">
        <label class="label">Last Name</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="text" placeholder="Last Name" name="last_name" maxlength="30" required=""
            id="id_last_name" />
          <span class="icon is-small is-left">
            <i class="fas fa-l"></i>
          </span>
        </p>
      </div>
  
      <!-- Email -->
      <div class="field">
        <label class="label">Email</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="email" placeholder="Email" name="email" maxlength="60" required="" id="id_email" />
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </p>
      </div>
  
      <!-- Phone Number -->
      <div class="field">
        <label class="label">Phone Number</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="tel" pattern="[0-9]{10}" placeholder="3061234567" name="phone" maxlength="10"
            required="" id="id_phone" />
          <span class="icon is-small is-left">
            <i class="fas fa-phone"></i>
          </span>
        </p>
      </div>

      <!--Question-->
      <div class=""field">
        <label class=""label">Any Questions</label>
        <p class="control has-icons-left has-icons-right">
            <input class="input" type="text" placeholder="Questions" autofocus="" name="questions" maxlength="150"
            required="" id="que" />
          <span class="icon is-small is-left">
            <i class="fas fa-Q"></i>
        </p>
    </div>

      <!--Donate Button-->
    <div class="field">
        <p class="control">
          <br style="display:block; margin: 5px 0;">
          <button class="button is-primary is-light">Send</button>
        </p>
      </div>

  </div>
</div>

{% endblock content %}

base/templates/base/home.html
{% extends 'main.html'%}

{% block content%}
<section class="hero is-medium is-info has-background mainsplash">
  <div class="hero-body ">
    {% if request.user.is_authenticated %}
    <p class="title is-size-1 herotitle">Welcome, {{request.user}}!</p>
    {% else %}
    <p class="title is-size-1 herotitle">Live With Peace Of Mind
    </p>
    {% endif %}
    <p class="subtitle herosubtitle title is-size-2">We're here for you when times are tough</p>
  </div>
</section>

<section class="section">
  <div class="tile is-ancestor">

    <div class="tile is-parent is-6">
      <article class="tile is-child box">
        <p class="title">Consider donating</p>

        <div class="content">
          <p>Volunteering can indeed prove to be beneficial for us and it can even help you become a better person in the process and we will always be able to remember the support we brought others when they were at a time of need.</p>
          <br>
          <a class="button is-primary" href="{% url 'donationpage' %}">Read more</a>
        </div>
      </article>
    </div>
    
    <div class="tile is-parent is-6">
      <article class="tile is-child box">
        <p class="title">Volunteer</p>
        <div class="content">
          <p>Help people around the community get enough to eat!<br>Your gift will be used to touch the lives of families around the world experiencing hunger.</p>
          <br>
          <a class="button is-primary" href="{% url 'volunteer' %}">Read more</a>
        </div>
      </article>
    </div>
  </div>
</section>

{% endblock content%}

base/templates/base/login.html
{% extends 'main.html'%}

{% block content%}

{% if messages %}
<article class="message is-danger" id="delete">
    <div class="message-header">
      <p>Attention</p>
      <button class="delete" aria-label="delete" onclick="myFunction()"></button>
    </div>
    <div class="message-body">
        <ul class="messages">

            {% for message in messages %}
            <li style="text-align:center;"> {{ message }}</li>
            {% endfor %}
        </ul> 
    </div>
</article>

{% endif %}


<div class="hero-body mainsplash">
    <div class="container">
        <div class="columns is-centered">
            <div class="column is-4 is">
                <form method="POST" action="" class="box">
                    {% csrf_token %}

                    <p class="title">Login</p>
                    <hr>
                    <label for="" class="label">
                    Username
                    </label>
                    <div class="field">
                        <p class="control has-icons-left ">
                            <input class="input" type="text" name="username" type="email" placeholder="Username">
                            <span class="icon is-small is-left">
                            <i class="fas fa-user"></i>
                            </span>
                        </p>
                    </div>
                    <label for="" class="label">
                    Password
                    </label>
                    <div class="field">
                        <p class="control has-icons-left">
                            <input type="Password" name="password" class="input" type="password" placeholder="Password">
                            <span class="icon is-small is-left">
                            <i class="fas fa-lock"></i>
                            </span>
                        </p>
                    </div>
                    <br>
                    <button type="submit" value="Login" class="button is-link">Login</button>
                    <hr>
                    <h1>Need to register? <a href="register/"> Sign up </a></h1>
                </form>
            </div>
        </div>
    </div>
</div>



{% endblock content%}

base/templates/base/room.html
{% extends 'main.html'%} {% block content%} {% endblock content%}

base/templates/base/volunteer.html
{% extends 'main.html' %} {% block content %}
<div class="container is-max-desktop">
  <div class="notification is-secondary is-light">
    <div class="title">Volunteer</div>
    <p>
      You can always choose to be part of our large community and help us serve the less fortunate.
    </p>
    <br>
          <a class="button" href="{% url 'volunteerForm' %}">Volunteer now</a>
  </div>
</div>

{% endblock content %}

base/templates/base/volunteerform.html
{% extends 'main.html' %} 
{% block content %}
<div class="container">
  <div class="notification is-secondary is-light">
    <div class="title">Volunteer</div>


    <!-- First Name -->
    <div class="field" style="line-height:2rem;">
        <label class="label">First Name</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="text" placeholder="First Name" autofocus="" name="first_name" maxlength="30"
            required="" id="id_first_name" />
          <span class="icon is-small is-left">
            <i class="fas fa-f"></i>
          </span>
        </p>
      </div>
  
      <!-- Last Name -->
      <div class="field">
        <label class="label">Last Name</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="text" placeholder="Last Name" name="last_name" maxlength="30" required=""
            id="id_last_name" />
          <span class="icon is-small is-left">
            <i class="fas fa-l"></i>
          </span>
        </p>
      </div>
  
      <!-- Email -->
      <div class="field">
        <label class="label">Email</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="email" placeholder="Email" name="email" maxlength="60" required="" id="id_email" />
          <span class="icon is-small is-left">
            <i class="fas fa-envelope"></i>
          </span>
        </p>
      </div>
  
      <!-- Phone Number -->
      <div class="field">
        <label class="label">Phone Number</label>
        <p class="control has-icons-left has-icons-right">
          <input class="input" type="tel" pattern="[0-9]{10}" placeholder="3061234567" name="phone" maxlength="10"
            required="" id="id_phone" />
          <span class="icon is-small is-left">
            <i class="fas fa-phone"></i>
          </span>
        </p>
      </div>

      <!--Donate Button-->
    <div class="field has-text-centered">
        <p class="control">
          <br style="display:block; margin: 5px 0;">
          <a class="button">Volunteer now</a>
        </p>
      </div>

  </div>
</div>

{% endblock content %}